# Generated by Django 4.1.3 on 2022-11-17 05:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('seller', '0006_remove_city_region_remove_region_country'),
        ('product_category', '0003_alter_category_parent'),
        ('product', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='seller',
            field=models.ForeignKey(default=4, on_delete=django.db.models.deletion.CASCADE, related_name='products', to='seller.seller'),
            preserve_default=False,
        ),
        migrations.CreateModel(
            name='Coupon',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('limit_amount', models.PositiveIntegerField()),
                ('limit_quantity', models.PositiveIntegerField()),
                ('status', models.CharField(choices=[('seller', 'seller'), ('category', 'category'), ('product', 'product'), ('general', 'general'), ('brand', 'brand')], max_length=20)),
                ('brand', models.ManyToManyField(related_name='coupons', to='product_category.brand')),
                ('category', models.ManyToManyField(related_name='coupons', to='product_category.category')),
                ('product', models.ManyToManyField(related_name='coupons', to='product.product')),
                ('seller', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='coupons', to='seller.seller')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Collection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=255)),
                ('image', models.ImageField(upload_to='products/collections/')),
                ('status', models.CharField(choices=[('seller', 'seller'), ('category', 'category'), ('product', 'product'), ('general', 'general'), ('brand', 'brand')], max_length=20)),
                ('brand', models.ManyToManyField(related_name='collections', to='product_category.brand')),
                ('category', models.ManyToManyField(related_name='collections', to='product_category.category')),
                ('product', models.ManyToManyField(related_name='collections', to='product.product')),
                ('seller', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='collections', to='seller.seller')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
