# Generated by Django 4.1.3 on 2022-11-10 15:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('product_category', '0002_alter_category_gender_alter_category_image'),
        ('seller', '0002_city_region_region_country_seller_department'),
    ]

    operations = [
        migrations.AlterField(
            model_name='city',
            name='region',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='seller.region'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='region',
            name='country',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='seller.country'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='seller',
            name='department',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='sellers', to='product_category.department'),
            preserve_default=False,
        ),
    ]
