# Generated by Django 4.1.3 on 2022-11-17 05:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('seller', '0005_alter_contact_email_alter_contact_phone'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='city',
            name='region',
        ),
        migrations.RemoveField(
            model_name='region',
            name='country',
        ),
    ]
