# Generated by Django 4.1.3 on 2022-11-21 16:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('seller', '0006_remove_city_region_remove_region_country'),
    ]

    operations = [
        migrations.AddField(
            model_name='seller',
            name='logo',
            field=models.ImageField(default=1, upload_to='logo/'),
            preserve_default=False,
        ),
    ]
