# Generated by Django 4.1.3 on 2022-11-21 16:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('seller', '0007_seller_logo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='seller',
            name='logo',
            field=models.ImageField(blank=True, null=True, upload_to='logo/'),
        ),
    ]
