# Generated by Django 4.1.3 on 2022-11-23 18:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('seller', '0008_alter_seller_logo'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='seller',
            name='logo',
        ),
    ]
